# Generated by Django 3.1.7 on 2021-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='banner',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
